

server:
  port: 8081

spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: daiveekam
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: IMMEDIATE







