

server:
  port:8080

spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: daiveekam
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update






