


server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authentication-ms
          uri: http://localhost:8081
          predicates:
            -Path=/api/v1/auth/**


