


server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authentication-ms
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: admin-ms
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/admin/**
        - id: user-ms
          uri:  http://localhost:8083
          predicates:
              - Path=/api/v1/user/**




